name: Cypress Tests

on:
  push:        # roda em qualquer push
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    env: # ðŸ‘ˆ define as variÃ¡veis a partir dos secrets
      LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

    steps:
      - name: Baixando projeto
        uses: actions/checkout@v4

      - name: Instalando dependÃªncias
        run: npm ci

      - name: Executando teste cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/login.cy.js

      - name: Subindo relatÃ³rio
        if: always() # Sempre sobe, mesmo se quebrar
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: mochawesome-report
          retention-days: 3
